### ISSUE TITLE
Implement 2D, 3D Bresenham function.

### ISSUE THREAD

**Issue by EmilyMatt** [EmilyMatt/mapping-rs#9]
An important function of converting point clouds to a viable occupancy grid, is a line-drawing function.
Bresenham's line algorithm is a solid place to start.
This function should be implemented for both 2D and 3D space(hall of fame spot if you can implement it using a const generic).
the function should also take into consideration that the map resolution may not be 1:1

More about Bresenham's line algorithm:
https://en.wikipedia.org/wiki/Bresenham%27s_line_algorithm
https://gist.github.com/john-science/2ba8fbbb7d008b0d1f15

**Comment by EyalBrilling** [comment]
i will be happy to work on it. 
Where should i save it at the folder structure?

**Comment by EmilyMatt** [comment]
I think
algorithms/src/bresenham/mod.rs is a good place :)

**Comment by EmilyMatt** [comment]
@EyalBrilling is there any progress on this? Should I unassign?

**Comment by EyalBrilling** [comment]
@EmilyMatt Yeah i will unassign me for now. thank you

**Comment by EmilyMatt** [comment]
Done and merged
